In [7]:
import numpy as np

def full_adder(x, y, c):
    z = (x ^ y) ^ c
    c_out = (x & y) | (x & c) | (y & c)
    return z, c_out

inputs = [(x, y, c) for x in (0,1) for y in (0,1) for c in (0,1)]
matrix = np.zeros((4,8), dtype=int)
row_labels = {(0,0):0, (0,1):1, (1,0):2, (1,1):3}

for col, (x, y, c) in enumerate(inputs):
    z, c_out = full_adder(x, y, c)
    row = row_labels[(z, c_out)]
    matrix[row, col] = 1

print(matrix)


[[1 0 0 0 0 0 0 0]
 [0 0 0 1 0 1 1 0]
 [0 1 1 0 1 0 0 0]
 [0 0 0 0 0 0 0 1]]


In [19]:
import numpy as np
matrix = np.zeros((4, 8), dtype=int)
rows= {(0,0):0, (0,1):1, (1,0):2, (1,1):3}

col = 0
for x in (0,1):
    for y in (0,1):
        for c in (0,1):
            z = (x ^ y) ^ c         
            c_out = (x & y) | (x & c) | (y & c)
        
            row = rows[(z, c_out)]
            matrix[row, col] = 1
            
            col += 1

print("The matrix: ")
print(matrix)


The matrix: 
[[1 0 0 0 0 0 0 0]
 [0 0 0 1 0 1 1 0]
 [0 1 1 0 1 0 0 0]
 [0 0 0 0 0 0 0 1]]
